### PR TITLE
Penguin + Redox = Wireless Penguinox

### PR DESCRIPTION
**Pull request by azhizhinov**
Penguin + Redox = Wireless Penguinox

### CODE REVIEW

**Comment by gorbit99** [comment]
The name's somewhat confusing, as penguin itself is already a redox clone. If I were to name it, I would give it a stupid nickname, like flying penguin or similar.

Also, not sure about the wireless solution of the original redox. I know it's very efficient, but it might be better to use a drop in micro Pro replacement with low powerstate Bluetooth support and use zmk with it to get a dongleless keyboard. Especially as the Pro micro isn't really recommended for qmk anymore.

**Comment by azhizhinov** [comment]
Hello.
Thanks for your time.
I'm not insist, if no, then no. ;-)
But why ProMicro is not recommended any more?

**Comment by gorbit99** [comment]
They have just enough just enough flash currently to support the most recent version of qmk, and even that only if you enable all sorts of optimizations and don't enable all effects at once. This could change if qmk gets enough updates, so they aren't recommended anymore.

**Comment by azhizhinov** [comment]
Hello.
Thanks for your time.
You can name it as you want, Penguin-w as example.
If you found this commit inappropriate, please decline, it's fine.
Good luck.

**Pull request closed without merging**
